# Generated by Django 4.2.10 on 2024-02-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Natjecanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportovi.sport')),
            ],
        ),
        migrations.CreateModel(
            name='RezultatUtakmice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezultat_domacin', models.IntegerField()),
                ('razultat_gost', models.IntegerField()),
                ('domacin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domacin', to='sportovi.tim')),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gost', to='sportovi.tim')),
                ('natjecanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportovi.natjecanje')),
            ],
        ),
        migrations.AddField(
            model_name='natjecanje',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportovi.sport'),
        ),
        migrations.AddField(
            model_name='natjecanje',
            name='tim',
            field=models.ManyToManyField(to='sportovi.tim'),
        ),
    ]
