# Generated by Django 4.2.10 on 2024-02-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportovi', '0002_alter_rezultatutakmice_domacin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezultatutakmice',
            old_name='razultat_gost',
            new_name='rezultat_gost',
        ),
    ]
