# Generated by Django 4.2.10 on 2024-02-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportovi', '0003_rename_razultat_gost_rezultatutakmice_rezultat_gost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezultatutakmice',
            name='rezultat_domacin',
        ),
        migrations.RemoveField(
            model_name='rezultatutakmice',
            name='rezultat_gost',
        ),
    ]
